name: CI

on:
    pull_request:
    push:
        branches:
            - "main"

env:
    CI: true

jobs:
    prepare-yarn-cache:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "yarn"
            - run: yarn install --mode=skip-build
              env:
                  YARN_ENABLE_SCRIPTS: false # disable post-install scripts
    yarn:
        runs-on: ubuntu-22.04
        needs: prepare-yarn-cache
        strategy:
            matrix:
                script:
                    - yarn build --exclude apps/www --exclude apps/infra && yarn lint
                    - yarn build --exclude apps/www --exclude apps/infra && yarn prettier
                    - yarn build --since-branch=main
                    - yarn test
                    - yarn constraints
                    - yarn changeset status --since=main
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 100
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "yarn"
            - run: git fetch origin main:main
            - run: yarn install --mode=skip-build && ${{ matrix.script }}
    changeset:
        runs-on: ubuntu-22.04
        needs: prepare-yarn-cache
        steps:
            - uses: actions/checkout@v2
            - name: Get changed files in the .changeset folder
              id: changed-files
              uses: tj-actions/changed-files@v29
              with:
                  files: |
                      .changeset/**/*.md
            - name: Check if any changesets contain minor changes
              id: find-changeset
              if: steps.set-blocks.outputs.blocks == ''
              run: |
                  echo "Checking for changesets marked as minor"
                  echo '::set-output name=found::false'
                  for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
                      echo '::set-output name=found::true'
                  done
            - name: Add label
              if: steps.find-changeset.outputs.found == 'false'
              run: exit 1
