name: CI

on:
    pull_request:
    push:
        branches:
            - "main"

env:
    CI: true

jobs:
    prepare-yarn-cache:
        runs-on: ubuntu-22.04
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: "16"
                  cache: "yarn"
            - run: yarn install --mode=skip-build
              env:
                  YARN_ENABLE_SCRIPTS: false # disable post-install scripts
    yarn:
        runs-on: ubuntu-22.04
        needs: prepare-yarn-cache
        strategy:
            matrix:
                script:
                    - yarn build --exclude apps/* && yarn lint
                    - yarn build --exclude apps/* && yarn prettier
                    - yarn build --since-branch=main
                    - yarn test
                    - yarn constraints
                    - yarn changeset status --since=main
                node_version:
                    - 14
                    - 16
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 100
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node_version }}
                  cache: "yarn"
            - run: git fetch origin main:main
            - run: yarn install --mode=skip-build && ${{ matrix.script }}
